/**
 * Bundle Vercel serverless functions.
 *
 * Why: with root package.json `"type": "module"`, Vercel runs api functions as
 * unbundled ESM and compiles ONLY the entry file — imported .ts/.tsx helpers are
 * never compiled to .js, so they can't be resolved at runtime
 * (ERR_MODULE_NOT_FOUND / FUNCTION_INVOCATION_FAILED). See docs/EMAIL_SETUP.md.
 *
 * Fix: esbuild bundles each function's OWN relative helper code (api/_email/*)
 * into a single self-contained file. node_modules packages stay EXTERNAL — they
 * resolve fine at runtime (only the uncompiled TS helpers were the problem), and
 * keeping them external keeps the committed output tiny.
 *
 * Source entries are `_`-prefixed (`api/_send-invite.ts`) so Vercel ignores them;
 * the bundled `api/send-invite.js` is what Vercel serves. Run after changing any
 * function or email template:  npm run bundle:functions
 */
import { build } from 'esbuild'

const entries = [{ in: 'api/_send-invite.ts', out: 'api/send-invite.js' }]

for (const { in: entry, out } of entries) {
  await build({
    entryPoints: [entry],
    outfile: out,
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'esm',
    jsx: 'automatic',
    packages: 'external', // leave bare imports (resend, @react-email/*, @supabase/*) for Node to resolve
    logLevel: 'warning',
    banner: { js: '// GENERATED by scripts/bundle-functions.mts — do not edit. Source: api/_send-invite.ts' },
  })
  // eslint-disable-next-line no-console
  console.log(`bundled ${out}`)
}
