-- Sync the skills table to match the canonical list in src/site/data/industries.ts.
-- The original seed had a small, partially-mismatched subset; this replaces it entirely.

-- Null out all skill FK refs so we can safely replace the skills table.
UPDATE worker_skills SET skill_id = NULL WHERE skill_id IS NOT NULL;

DELETE FROM skills;

-- ── Construction ─────────────────────────────────────────────────────────────
INSERT INTO skills (id, industry_id, name, aliases) VALUES
  ('carpentry',      'construction', 'Carpentry',                   ARRAY['carpenter','woodwork','finish carpentry']),
  ('framing',        'construction', 'Framing',                     ARRAY['wood framing','stud framing','structural framing','rough framing']),
  ('drywall',        'construction', 'Drywall Installation',        ARRAY['drywall','sheetrock','gypsum board','drywall finishing']),
  ('concrete',       'construction', 'Concrete Work',               ARRAY['concrete pouring','concrete finishing','flatwork','concrete placement']),
  ('masonry',        'construction', 'Masonry',                     ARRAY['bricklaying','block laying','stonework','tuck pointing']),
  ('plumbing',       'construction', 'Plumbing',                    ARRAY['plumber','pipe fitting','pipefitting','drain work']),
  ('electrical',     'construction', 'Electrical Wiring',           ARRAY['electrician','electrical','wiring','conduit']),
  ('hvac',           'construction', 'HVAC',                        ARRAY['hvac tech','heating and cooling','air conditioning','refrigeration','mechanical']),
  ('roofing',        'construction', 'Roofing',                     ARRAY['roofer','shingles','flat roofing','metal roofing']),
  ('welding',        'construction', 'Welding (MIG/TIG)',            ARRAY['welder','mig welding','tig welding','stick welding','arc welding']),
  ('painting_int',   'construction', 'Interior Painting',           ARRAY['painter','interior paint','wall painting']),
  ('painting_ext',   'construction', 'Exterior Painting',           ARRAY['exterior paint','house painting','spray painting']),
  ('flooring',       'construction', 'Flooring Installation',       ARRAY['flooring','hardwood floors','laminate','vinyl plank','LVP']),
  ('tile',           'construction', 'Tile Setting',                ARRAY['tile setter','ceramic tile','porcelain tile','tile installation']),
  ('landscaping',    'construction', 'Landscape Installation',      ARRAY['landscaping','lawn care','hardscaping','irrigation']),
  ('excavation',     'construction', 'Excavation',                  ARRAY['excavating','digging','grading','earthwork']),
  ('heavy_equip',    'construction', 'Heavy Equipment Operation',   ARRAY['equipment operator','heavy machinery','bulldozer','backhoe','excavator']),
  ('blueprint',      'construction', 'Blueprint Reading',           ARRAY['blueprints','plan reading','schematic reading','technical drawings']),
  ('osha',           'construction', 'OSHA Safety Compliance',      ARRAY['osha 10','osha 30','safety','job site safety','hazmat']),
  ('estimating',     'construction', 'Cost Estimating',             ARRAY['estimator','take-offs','bid preparation','project estimation']),
  ('steel',          'construction', 'Steel Erection',              ARRAY['ironworker','structural steel','steel framing','metal building']),
  ('insulation',     'construction', 'Insulation Installation',     ARRAY['insulation','spray foam','batt insulation','blown-in insulation']),
  ('waterproofing',  'construction', 'Waterproofing',               ARRAY['waterproof','moisture barrier','foundation waterproofing']),
  ('scaffolding',    'construction', 'Scaffolding',                 ARRAY['scaffold erection','scaffold','aerial lift']),
  ('demolition',     'construction', 'Demolition',                  ARRAY['demo','selective demo','abatement']),
  ('cabinets',       'construction', 'Cabinet Making',              ARRAY['cabinetry','kitchen cabinets','custom cabinets','millwork']),
  ('forklift',       'construction', 'Forklift Operation',          ARRAY['forklift certified','forklift operator','pallet jack']),
  ('crane',          'construction', 'Crane Operation',             ARRAY['crane operator','tower crane','mobile crane']),
  ('solar',          'construction', 'Solar Panel Installation',    ARRAY['solar installer','photovoltaic','PV systems','solar']),
  ('sprinkler',      'construction', 'Sprinkler System Installation',ARRAY['fire suppression','sprinkler fitter','fire protection']),
  ('concrete_finish','construction', 'Concrete Finishing',          ARRAY['flatwork finishing','troweling','decorative concrete']),
  ('rebar',          'construction', 'Rebar Installation',          ARRAY['iron worker','rebar tying','reinforcing steel']),
  ('acoustic',       'construction', 'Acoustic Ceiling',            ARRAY['drop ceiling','suspended ceiling','T-bar ceiling']),
  ('epoxy',          'construction', 'Epoxy Flooring',              ARRAY['epoxy coating','industrial flooring','floor coating']),
  ('metal_framing',  'construction', 'Metal Framing',               ARRAY['light gauge steel','cold formed steel','metal studs']),
  ('stucco',         'construction', 'Stucco Application',          ARRAY['stucco','EIFS','plaster','lath and plaster']),
  ('foundation',     'construction', 'Foundation Work',             ARRAY['footings','foundation forms','grade beams']),
  ('surveying',      'construction', 'Site Surveying',              ARRAY['surveyor','total station','GPS surveying','layout']),
  ('glass',          'construction', 'Glass & Glazing',             ARRAY['glazier','window installation','storefront','curtain wall']),
  ('form_setting',   'construction', 'Form Setting',                ARRAY['concrete forms','ICF','form carpenter']);

-- ── Healthcare ───────────────────────────────────────────────────────────────
INSERT INTO skills (id, industry_id, name, aliases) VALUES
  ('patient_care',       'healthcare', 'Patient Care',                     ARRAY['direct patient care','bedside care','personal care']),
  ('vitals',             'healthcare', 'Vital Signs Monitoring',           ARRAY['vitals','blood pressure monitoring','pulse ox','temperature check']),
  ('medication_admin',   'healthcare', 'Medication Administration',        ARRAY['med pass','medication management','dispensing medication']),
  ('wound_care',         'healthcare', 'Wound Care',                       ARRAY['dressing changes','wound assessment','wound irrigation']),
  ('iv_therapy',         'healthcare', 'IV Therapy',                       ARRAY['IV insertion','intravenous therapy','peripheral IV','IV start']),
  ('cpr_aed',            'healthcare', 'CPR / AED Certified',              ARRAY['CPR','AED','BLS','basic life support','ACLS']),
  ('ehr',                'healthcare', 'Electronic Health Records (EHR)',   ARRAY['EHR','EMR','Epic','Cerner','electronic charting']),
  ('phlebotomy',         'healthcare', 'Phlebotomy',                       ARRAY['blood draw','venipuncture','specimen collection']),
  ('pta',                'healthcare', 'Physical Therapy Assistance',      ARRAY['PTA','physical therapy aide','therapy support']),
  ('ota',                'healthcare', 'Occupational Therapy Assistance',  ARRAY['OTA','occupational therapy aide']),
  ('medical_terminology','healthcare', 'Medical Terminology',              ARRAY['clinical terminology','medical vocabulary']),
  ('hipaa',              'healthcare', 'HIPAA Compliance',                 ARRAY['HIPAA','patient privacy','healthcare compliance']),
  ('care_planning',      'healthcare', 'Care Planning',                    ARRAY['care plans','treatment planning','care coordination']),
  ('catheter',           'healthcare', 'Catheter Care',                    ARRAY['foley catheter','urinary catheter','catheterization']),
  ('dementia_care',      'healthcare', 'Dementia Care',                    ARRAY['Alzheimers care','memory care','cognitive impairment care']),
  ('pediatric',          'healthcare', 'Pediatric Care',                   ARRAY['pediatrics','childcare nursing','neonatal']),
  ('mental_health',      'healthcare', 'Mental Health Support',            ARRAY['behavioral health','psychiatric care','crisis intervention']),
  ('dialysis',           'healthcare', 'Dialysis Care',                    ARRAY['hemodialysis','peritoneal dialysis','renal care']),
  ('post_surgical',      'healthcare', 'Post-Surgical Care',               ARRAY['post-op care','surgical recovery','PACU']),
  ('hha',                'healthcare', 'Home Health Aide (HHA)',           ARRAY['HHA','home care aide','personal care aide']),
  ('cna',                'healthcare', 'Certified Nursing Assistant (CNA)',ARRAY['CNA','nursing aide','nursing assistant']),
  ('medical_coding',     'healthcare', 'Medical Coding (ICD-10)',          ARRAY['medical billing','ICD-10','CPT codes','medical coder']),
  ('sterilization',      'healthcare', 'Sterilization & Disinfection',     ARRAY['sterilization','infection prevention','autoclave']),
  ('patient_lift',       'healthcare', 'Patient Lifting & Transfer',       ARRAY['patient transfer','Hoyer lift','mechanical lift','body mechanics']),
  ('infection_control',  'healthcare', 'Infection Control',                ARRAY['infection prevention','PPE','isolation precautions','hand hygiene']),
  ('emergency_response', 'healthcare', 'Emergency Response',               ARRAY['emergency care','code blue','rapid response','first aid']),
  ('nutrition_support',  'healthcare', 'Nutrition Support',                ARRAY['tube feeding','enteral nutrition','dietary support','feeding assistance']),
  ('respiratory',        'healthcare', 'Respiratory Therapy',              ARRAY['respiratory care','nebulizer','oxygen therapy','ventilator']),
  ('scheduling_docs',    'healthcare', 'Scheduling & Documentation',       ARRAY['charting','clinical documentation','scheduling']),
  ('glucose_monitoring', 'healthcare', 'Blood Glucose Monitoring',         ARRAY['blood sugar','glucometer','diabetic care','glucose check']),
  ('tracheostomy',       'healthcare', 'Tracheostomy Care',                ARRAY['trach care','tracheotomy','airway management']),
  ('specimen',           'healthcare', 'Specimen Collection',              ARRAY['lab specimens','swab collection','urine specimen','cultures']),
  ('ekg',                'healthcare', 'EKG / ECG Monitoring',             ARRAY['EKG','ECG','cardiac monitoring','12-lead EKG']),
  ('pain_management',    'healthcare', 'Pain Management',                  ARRAY['pain assessment','pain scale','comfort care']),
  ('fall_prevention',    'healthcare', 'Fall Prevention',                  ARRAY['fall risk assessment','bed alarms','safe mobility']),
  ('behavioral_support', 'healthcare', 'Behavioral Support',               ARRAY['behavior management','de-escalation','ABA therapy support']),
  ('palliative',         'healthcare', 'Palliative Care',                  ARRAY['hospice care','end of life care','comfort care']),
  ('colostomy',          'healthcare', 'Colostomy / Ostomy Care',          ARRAY['ostomy','colostomy bag','stoma care']),
  ('med_dispensing',     'healthcare', 'Medication Dispensing',            ARRAY['medication cart','Pyxis','automated dispensing']),
  ('bed_bath',           'healthcare', 'Bathing & Hygiene Assistance',     ARRAY['bed bath','personal hygiene','ADL assistance','activities of daily living']);

-- ── Manufacturing ────────────────────────────────────────────────────────────
INSERT INTO skills (id, industry_id, name, aliases) VALUES
  ('assembly_line',      'manufacturing', 'Assembly Line Operation',           ARRAY['assembly','production line','line operator']),
  ('quality_control',    'manufacturing', 'Quality Control (QC)',              ARRAY['QC','quality assurance','QA','inspection','quality inspection']),
  ('cnc',                'manufacturing', 'CNC Machine Operation',             ARRAY['CNC','CNC machinist','CNC operator','computer numerical control']),
  ('forklift_mfg',       'manufacturing', 'Forklift Certification',            ARRAY['forklift','forklift operator','pallet jack','reach truck']),
  ('mig_welding',        'manufacturing', 'MIG Welding',                       ARRAY['MIG','wire welding','GMAW','gas metal arc']),
  ('tig_welding',        'manufacturing', 'TIG Welding',                       ARRAY['TIG','GTAW','heliarc','gas tungsten arc']),
  ('warehouse_mgmt',     'manufacturing', 'Warehouse Management',              ARRAY['warehouse','WMS','fulfillment','distribution']),
  ('inventory_control',  'manufacturing', 'Inventory Control',                 ARRAY['inventory management','cycle counting','stockroom','parts management']),
  ('lean',               'manufacturing', 'Lean Manufacturing',                ARRAY['lean','5S','kaizen','continuous improvement','lean production']),
  ('six_sigma',          'manufacturing', 'Six Sigma',                         ARRAY['six sigma green belt','six sigma black belt','DMAIC','process improvement']),
  ('preventive_maint',   'manufacturing', 'Preventive Maintenance',            ARRAY['PM','equipment maintenance','machine maintenance','maintenance tech']),
  ('blueprint_mfg',      'manufacturing', 'Blueprint Reading',                 ARRAY['blueprints','engineering drawings','GD&T','technical drawings']),
  ('material_handling',  'manufacturing', 'Material Handling',                 ARRAY['material movement','shipping and receiving','logistics']),
  ('production_sched',   'manufacturing', 'Production Scheduling',             ARRAY['production planning','master schedule','capacity planning']),
  ('spc',                'manufacturing', 'Statistical Process Control (SPC)', ARRAY['SPC','control charts','process control','statistical quality control']),
  ('hydraulics',         'manufacturing', 'Hydraulic Systems',                 ARRAY['hydraulics','hydraulic maintenance','fluid power']),
  ('pneumatics',         'manufacturing', 'Pneumatic Systems',                 ARRAY['pneumatics','air systems','compressed air']),
  ('robotics',           'manufacturing', 'Robotics Operation',                ARRAY['robot operator','robotic arm','automation','FANUC','ABB robots']),
  ('soldering',          'manufacturing', 'Soldering',                         ARRAY['electronics soldering','PCB soldering','hand soldering','wave soldering']),
  ('packaging',          'manufacturing', 'Packaging & Labeling',              ARRAY['packaging','pack out','labeling','kitting']),
  ('osha_mfg',           'manufacturing', 'OSHA Safety Compliance',            ARRAY['OSHA','safety compliance','lock out tag out','LOTO','PPE']),
  ('erp',                'manufacturing', 'ERP Systems',                       ARRAY['SAP','Oracle','ERP','MRP','manufacturing software']),
  ('injection_molding',  'manufacturing', 'Injection Molding',                 ARRAY['plastic injection','injection molder','thermoplastic molding']),
  ('stamping',           'manufacturing', 'Metal Stamping & Pressing',         ARRAY['stamping press','die stamping','progressive die','metal forming']),
  ('haccp',              'manufacturing', 'Food Safety / HACCP',               ARRAY['HACCP','food safety','GMP','good manufacturing practices','food grade']),
  ('plc',                'manufacturing', 'PLC Programming',                   ARRAY['PLC','programmable logic controller','Allen-Bradley','Siemens PLC','ladder logic']),
  ('additive_mfg',       'manufacturing', '3D Printing / Additive Manufacturing',ARRAY['3D printing','additive manufacturing','FDM','SLA printing']),
  ('chemical_handling',  'manufacturing', 'Chemical Handling',                 ARRAY['hazmat','chemical safety','MSDS','SDS','hazardous materials']),
  ('precision_measuring','manufacturing', 'Precision Measuring',               ARRAY['metrology','calipers','micrometers','CMM','gauging']),
  ('torque_tools',       'manufacturing', 'Torque Tools & Fastening',          ARRAY['torque wrench','impact wrench','pneumatic tools','torque specs']),
  ('grinding',           'manufacturing', 'Surface Grinding',                  ARRAY['grinding','angle grinder','bench grinder','cylindrical grinding']),
  ('lathe',              'manufacturing', 'Lathe Operation',                   ARRAY['lathe','turning','manual lathe','CNC lathe']),
  ('milling',            'manufacturing', 'Milling Machine Operation',         ARRAY['milling','manual mill','vertical mill','Bridgeport']),
  ('die_setting',        'manufacturing', 'Die Setting',                       ARRAY['die setter','tooling changeover','press setup']),
  ('extrusion',          'manufacturing', 'Extrusion Operation',               ARRAY['extruder','plastic extrusion','aluminum extrusion','extrusion operator']),
  ('heat_treating',      'manufacturing', 'Heat Treating',                     ARRAY['heat treatment','annealing','hardening','tempering']),
  ('ndt',                'manufacturing', 'Non-Destructive Testing (NDT)',     ARRAY['NDT','NDE','ultrasonic testing','dye penetrant','magnetic particle']),
  ('calibration',        'manufacturing', 'Calibration',                       ARRAY['instrument calibration','gage calibration','metrology']),
  ('kanban',             'manufacturing', 'Kanban Systems',                    ARRAY['kanban','pull system','JIT','just in time','visual management']),
  ('iso9001',            'manufacturing', 'ISO 9001 Compliance',               ARRAY['ISO 9001','ISO certification','quality management system','QMS','AS9100']);
