// GENERATED by scripts/bundle-functions.mts — do not edit. Source: api/_send-invite.ts

// api/_send-invite.ts
import * as React from "react";
import { createClient } from "@supabase/supabase-js";

// api/_email/templates/InviteEmail.tsx
import { Section as Section2 } from "@react-email/components";

// api/_email/EmailLayout.tsx
import {
  Body,
  Button as REButton,
  Container,
  Head,
  Html,
  Img,
  Link,
  Preview,
  Section,
  Text
} from "@react-email/components";

// api/_email/emailConstants.ts
var COLORS = {
  headerBg: "#0A232D",
  // dark teal, used for the header band
  buttonBg: "#6D7531",
  // brand olive, used for primary CTA
  footerBg: "#F6F2E8",
  // warm sandy, used inside the frame for the footer band
  canvasBg: "#FFFFFF",
  // white, used behind the email frame
  cardBg: "#FFFFFF",
  // content card
  bodyText: "#1C3D4A",
  // body copy and headings (mid teal)
  mutedText: "#6B7280",
  // secondary text, footer
  border: "#E5E7EB",
  // dividers and card borders
  buttonText: "#FFFFFF",
  // text on primary button
  headerText: "#FFFFFF",
  // text on header band
  secondaryCardBg: "#F9FAFB"
  // detail card inside body
};
var FONTS = {
  sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif'
};
var SENDER = {
  fromName: "Krewtree",
  fromEmail: "noreply@mail.krewtree.com",
  replyTo: "support@krewtree.com",
  unsubscribeMailto: "unsubscribe@krewtree.com"
};
var LEGAL = {
  entityName: "Krewtree",
  addressLine1: "[Street Address Placeholder]",
  addressLine2: "[City, State ZIP Placeholder]"
};
var URLS = {
  baseUrl: "https://krewtree.com",
  logoUrl: "https://ryigaxihlfqdwgjbgmcg.supabase.co/storage/v1/object/public/avatars/brand/krewtree-logo-horizontal-white.png",
  privacyUrl: "https://krewtree.com/privacy",
  termsUrl: "https://krewtree.com/terms"
};
var CATEGORY_LABELS = {
  applicants: "Applicants",
  messages: "Messages",
  jobs: "Jobs",
  pipeline: "Pipeline",
  account: "Account",
  regulix: "Regulix",
  security: "Security"
};
function preferencesUrl(category) {
  if (category === "security") return `${URLS.baseUrl}/settings/notifications`;
  return `${URLS.baseUrl}/settings/notifications#${category}`;
}
function unsubscribeUrl(token) {
  return `${URLS.baseUrl}/unsubscribe?token=${encodeURIComponent(token)}`;
}

// api/_email/EmailLayout.tsx
import { Fragment, jsx, jsxs } from "react/jsx-runtime";
function EmailLayout({
  preheader,
  category,
  unsubscribeUrl: unsubscribeUrl2,
  footer = "auto",
  children
}) {
  const isSecurity = category === "security";
  const isTransactional = footer === "transactional";
  return /* @__PURE__ */ jsxs(Html, { children: [
    /* @__PURE__ */ jsxs(Head, { children: [
      /* @__PURE__ */ jsx("meta", { name: "color-scheme", content: "light" }),
      /* @__PURE__ */ jsx("meta", { name: "supported-color-schemes", content: "light" })
    ] }),
    /* @__PURE__ */ jsx(Preview, { children: preheader }),
    /* @__PURE__ */ jsx(Body, { style: bodyStyle, children: /* @__PURE__ */ jsxs(Container, { style: outerContainer, children: [
      /* @__PURE__ */ jsx(Section, { style: headerSection, children: /* @__PURE__ */ jsx(Img, { src: URLS.logoUrl, alt: "Krewtree", width: "140", height: "32", style: logoStyle }) }),
      /* @__PURE__ */ jsx(Section, { style: bodySection, children }),
      /* @__PURE__ */ jsxs(Section, { style: footerSection, children: [
        isTransactional ? null : isSecurity ? /* @__PURE__ */ jsx(Text, { style: footerLine, children: "This is a security notification and cannot be turned off in your preferences." }) : /* @__PURE__ */ jsx(Text, { style: footerLine, children: /* @__PURE__ */ jsxs(Link, { href: preferencesUrl(category), style: footerLink, children: [
          "Manage ",
          CATEGORY_LABELS[category],
          " notification preferences"
        ] }) }),
        /* @__PURE__ */ jsx(Text, { style: footerLine, children: "You\u2019re receiving this because you have a Krewtree account." }),
        /* @__PURE__ */ jsxs(Text, { style: footerAddress, children: [
          LEGAL.entityName,
          /* @__PURE__ */ jsx("br", {}),
          LEGAL.addressLine1,
          /* @__PURE__ */ jsx("br", {}),
          LEGAL.addressLine2
        ] }),
        /* @__PURE__ */ jsxs(Text, { style: footerLegal, children: [
          /* @__PURE__ */ jsx(Link, { href: URLS.privacyUrl, style: footerLink, children: "Privacy" }),
          " \xB7 ",
          /* @__PURE__ */ jsx(Link, { href: URLS.termsUrl, style: footerLink, children: "Terms" }),
          unsubscribeUrl2 && /* @__PURE__ */ jsxs(Fragment, { children: [
            " \xB7 ",
            /* @__PURE__ */ jsx(Link, { href: unsubscribeUrl2, style: footerLink, children: "Unsubscribe" })
          ] })
        ] })
      ] })
    ] }) })
  ] });
}
function EmailButton({ href, children }) {
  return /* @__PURE__ */ jsx(REButton, { href, style: buttonStyle, children });
}
function EmailHeading({ children }) {
  return /* @__PURE__ */ jsx("h1", { style: headingStyle, children });
}
function EmailText({ children }) {
  return /* @__PURE__ */ jsx("p", { style: textStyle, children });
}
var bodyStyle = {
  backgroundColor: COLORS.canvasBg,
  fontFamily: FONTS.sans,
  margin: 0,
  padding: 0,
  WebkitFontSmoothing: "antialiased"
};
var outerContainer = {
  maxWidth: "600px",
  width: "100%",
  margin: "0 auto",
  padding: "0 0 24px 0"
};
var headerSection = {
  backgroundColor: COLORS.headerBg,
  padding: "20px 32px",
  borderTopLeftRadius: "8px",
  borderTopRightRadius: "8px",
  borderTop: `1px solid ${COLORS.border}`,
  borderLeft: `1px solid ${COLORS.border}`,
  borderRight: `1px solid ${COLORS.border}`
};
var logoStyle = {
  display: "block"
};
var bodySection = {
  backgroundColor: COLORS.cardBg,
  padding: "32px",
  borderLeft: `1px solid ${COLORS.border}`,
  borderRight: `1px solid ${COLORS.border}`
};
var footerSection = {
  backgroundColor: COLORS.footerBg,
  padding: "24px 32px",
  textAlign: "left",
  borderTop: `1px solid ${COLORS.border}`,
  borderLeft: `1px solid ${COLORS.border}`,
  borderRight: `1px solid ${COLORS.border}`,
  borderBottom: `1px solid ${COLORS.border}`,
  borderBottomLeftRadius: "8px",
  borderBottomRightRadius: "8px"
};
var footerLine = {
  fontSize: "13px",
  lineHeight: "20px",
  color: COLORS.mutedText,
  margin: "0 0 8px 0"
};
var footerLink = {
  color: COLORS.mutedText,
  textDecoration: "underline"
};
var footerAddress = {
  fontSize: "12px",
  lineHeight: "18px",
  color: COLORS.mutedText,
  margin: "16px 0 12px 0"
};
var footerLegal = {
  fontSize: "12px",
  lineHeight: "18px",
  color: COLORS.mutedText,
  margin: "0"
};
var headingStyle = {
  fontSize: "22px",
  lineHeight: "30px",
  fontWeight: 600,
  color: COLORS.bodyText,
  margin: "0 0 16px 0"
};
var textStyle = {
  fontSize: "15px",
  lineHeight: "24px",
  color: COLORS.bodyText,
  margin: "0 0 16px 0"
};
var buttonStyle = {
  backgroundColor: COLORS.buttonBg,
  color: COLORS.buttonText,
  padding: "12px 24px",
  borderRadius: "6px",
  fontSize: "15px",
  fontWeight: 600,
  textDecoration: "none",
  display: "inline-block",
  lineHeight: "20px"
};
var secondaryCardStyle = {
  backgroundColor: COLORS.secondaryCardBg,
  border: `1px solid ${COLORS.border}`,
  borderRadius: "6px",
  padding: "16px 20px",
  margin: "8px 0 20px 0"
};

// api/_email/templates/InviteEmail.tsx
import { jsx as jsx2, jsxs as jsxs2 } from "react/jsx-runtime";
function InviteEmail({ companyName, inviterName, joinUrl }) {
  const lead = inviterName ? `${inviterName} invited you to join ${companyName} on Krewtree.` : `You've been invited to join ${companyName} on Krewtree.`;
  return /* @__PURE__ */ jsxs2(
    EmailLayout,
    {
      preheader: `Join ${companyName} on Krewtree`,
      category: "account",
      footer: "transactional",
      children: [
        /* @__PURE__ */ jsxs2(EmailHeading, { children: [
          "You\u2019re invited to join ",
          companyName
        ] }),
        /* @__PURE__ */ jsx2(EmailText, { children: lead }),
        /* @__PURE__ */ jsx2(EmailText, { children: "Accept the invitation to set up your account and start working with the team." }),
        /* @__PURE__ */ jsx2(Section2, { style: { padding: "8px 0 8px 0" }, children: /* @__PURE__ */ jsx2(EmailButton, { href: joinUrl, children: "Accept invitation" }) }),
        /* @__PURE__ */ jsxs2(EmailText, { children: [
          "Or paste this link into your browser:",
          /* @__PURE__ */ jsx2("br", {}),
          /* @__PURE__ */ jsx2("a", { href: joinUrl, style: { color: COLORS.bodyText, wordBreak: "break-all" }, children: joinUrl })
        ] })
      ]
    }
  );
}

// api/_email/sendEmail.ts
import { Resend } from "resend";
var resend = new Resend(process.env.RESEND_API_KEY);
function fromHeader() {
  const address = process.env.EMAIL_FROM || SENDER.fromEmail;
  return `${SENDER.fromName} <${address}>`;
}
async function sendKrewtreeEmail(args) {
  const { to, subject, react, unsubscribeToken, idempotencyKey, tags } = args;
  const headers = {};
  if (unsubscribeToken) {
    const unsubUrl = unsubscribeUrl(unsubscribeToken);
    headers["List-Unsubscribe"] = `<mailto:${SENDER.unsubscribeMailto}?subject=unsubscribe&body=${encodeURIComponent(unsubscribeToken)}>, <${unsubUrl}>`;
    headers["List-Unsubscribe-Post"] = "List-Unsubscribe=One-Click";
  }
  if (idempotencyKey) {
    headers["Idempotency-Key"] = idempotencyKey;
  }
  return resend.emails.send({
    from: fromHeader(),
    to,
    replyTo: SENDER.replyTo,
    subject,
    react,
    headers,
    ...tags && { tags }
  });
}

// api/_send-invite.ts
var EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function firstHeader(value) {
  return Array.isArray(value) ? value[0] : value;
}
function parseBody(raw) {
  let obj = raw;
  if (typeof raw === "string") {
    try {
      obj = JSON.parse(raw);
    } catch {
      return null;
    }
  }
  if (!obj || typeof obj !== "object") return null;
  const b = obj;
  if (typeof b.email !== "string" || typeof b.token !== "string") return null;
  return {
    email: b.email.trim(),
    token: b.token,
    companyName: typeof b.companyName === "string" ? b.companyName.trim() : void 0,
    inviterName: typeof b.inviterName === "string" ? b.inviterName.trim() : void 0
  };
}
function siteOrigin(req) {
  const configured = process.env.PUBLIC_SITE_URL;
  if (configured) return configured.replace(/\/+$/, "");
  const host = firstHeader(req.headers["x-forwarded-host"]) ?? firstHeader(req.headers.host);
  const proto = firstHeader(req.headers["x-forwarded-proto"]) ?? "https";
  return host ? `${proto}://${host}` : "https://krewtree-app.vercel.app";
}
async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).json({ error: "method_not_allowed" });
    return;
  }
  const supabaseUrl = process.env.VITE_SUPABASE_URL;
  const anonKey = process.env.VITE_SUPABASE_ANON_KEY;
  const resendKey = process.env.RESEND_API_KEY;
  if (!supabaseUrl || !anonKey) {
    res.status(500).json({ error: "supabase_not_configured" });
    return;
  }
  if (!resendKey) {
    res.status(500).json({ error: "email_not_configured" });
    return;
  }
  const bearer = firstHeader(req.headers.authorization);
  const jwt = bearer?.startsWith("Bearer ") ? bearer.slice(7) : void 0;
  if (!jwt) {
    res.status(401).json({ error: "unauthenticated" });
    return;
  }
  const supabase = createClient(supabaseUrl, anonKey);
  const { data: userData, error: userErr } = await supabase.auth.getUser(jwt);
  if (userErr || !userData?.user) {
    res.status(401).json({ error: "unauthenticated" });
    return;
  }
  const body = parseBody(req.body);
  if (!body || !EMAIL_RE.test(body.email) || !body.token) {
    res.status(400).json({ error: "invalid_request" });
    return;
  }
  const joinUrl = `${siteOrigin(req)}/join?token=${encodeURIComponent(body.token)}`;
  const company = body.companyName || "a company";
  const subject = `You're invited to join ${company} on Krewtree`;
  try {
    const result = await sendKrewtreeEmail({
      to: body.email,
      subject,
      react: React.createElement(InviteEmail, {
        companyName: company,
        inviterName: body.inviterName,
        joinUrl
      }),
      // Dedupe retries of the same invite (token is unique per invite).
      idempotencyKey: `invite:${body.token.slice(0, 200)}`
    });
    if (result.error) {
      res.status(502).json({ error: "send_failed", detail: result.error.message });
      return;
    }
    res.status(200).json({ id: result.data?.id ?? null });
  } catch (err) {
    res.status(502).json({
      error: "send_failed",
      detail: err instanceof Error ? err.message : "unknown"
    });
  }
}
export {
  handler as default
};
